/**
 * Savood
 * denn nur lebendiges food tut gut
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Comment } from './comment';


export interface Offering {
    id?: string;
    name?: string;
    header?: string;
    creatorId?: number;
    bestByDate?: string;
    location?: string;
    avatarUrl?: string;
    requestedBy?: number;
    totalLikes?: string;
    totalSavoods?: string;
    totalComments?: string;
    comments?: Array<Comment>;
    time?: Date;
}
