/**
 * Savood
 * denn nur lebendiges food tut gut
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProfileAddress } from './profileAddress';


export interface Profile {
    id?: number;
    firstname?: string;
    lastname?: string;
    email?: string;
    phone?: string;
    address?: ProfileAddress;
    backgroundId?: string;
    avatarId?: string;
    description?: string;
    badges?: any;
}
