/**
 * Savood
 * denn nur lebendiges food tut gut
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Address } from './address';


export interface User {
    _id?: string;
    firstname?: string;
    lastname?: string;
    phone?: string;
    address?: Address;
    description?: string;
    badges?: Array<string>;
}
